version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Berlin"

    open-pull-requests-limit: 5

    labels:
      - "dependencies"

    commit-message:
      prefix: "deps"

    reviewers:
      - "NicDevTV"

    ignore:
      - dependency-name: "io.papermc.paper:paper-api"
        versions:
          - "[26.0,27.0)"

      - dependency-name: "com.velocitypowered:velocity-api"
        versions:
          - "[3.4.0-SNAPSHOT]"

    groups:
      gradle-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
