version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Berlin"

    open-pull-requests-limit: 5

    labels:
      - "dependencies"

    commit-message:
      prefix: "deps"

    reviewers:
      - "NicDevTV"

    groups:
      gradle-dependencies:
        patterns:
          - "*"

    ignore:
      - dependency-name: "org.jetbrains.kotlin:*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"