name: CraftRelay
version: "${version}"
main: tv.nicdev.craftrelay.platform.paper.CraftRelayPaperPlugin
description: Redis-backed Minecraft network synchronization
authors: ${authors}
api-version: "1.20.6"
load: STARTUP
